import { type Alert } from './types';

// Helper to get dates for today and yesterday
const today = new Date();
const yesterday = new Date();
yesterday.setDate(yesterday.getDate() - 1);

const createDeterministicTimestamp = (baseDate: Date, index: number) => {
  const d = new Date(baseDate);
  // Subtract hours deterministically to ensure consistent order
  d.setHours(d.getHours() - index, d.getMinutes() - (index * 15), d.getSeconds() - (index * 10));
  return d.toISOString();
};


export const initialAlerts: Alert[] = [
  {
    id: 'alert-1',
    time: createDeterministicTimestamp(today, 0),
    host: 'WEB-SERVER-03',
    alertType: 'DataExfiltration',
    score: 0.98,
    mitreTactic: 'TA0010',
    srcIp: '10.10.1.5',
    dstIp: '185.199.108.153',
    evidence: 'Large upload (50.2MB) to known file sharing site transfer.sh',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.95,
    supervisedClassifierScore: 0.99,
    topRuleHits: ['Exfiltration to File Sharing Site', 'Anomalous Data Transfer Size'],
    topFeatures: ['dst_ip:185.199.108.153', 'bytes_sent>50MB'],
  },
  {
    id: 'alert-2',
    time: createDeterministicTimestamp(today, 1),
    host: 'Strive-Linux',
    alertType: 'ProcessAnomaly',
    score: 0.87,
    mitreTactic: 'TA0002',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'Suspicious process chain: bash -> python3 -> curl',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.88,
    topRuleHits: ['Suspicious Process Chain', 'Script Spawning Network Tool'],
    topFeatures: ['parent:python3', 'child:curl'],
  },
  {
    id: 'alert-3',
    time: createDeterministicTimestamp(today, 2),
    host: 'DB-SERVER-01',
    alertType: 'LateralMovement',
    score: 0.76,
    mitreTactic: 'TA0008',
    srcIp: '10.0.0.8',
    dstIp: '10.0.0.12',
    evidence: 'Multiple failed SMB logon attempts followed by success from non-standard host',
    status: 'Investigating',
    ruleBasedScore: 0.6,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.7,
    topRuleHits: ['Brute-force attempt', 'Anomalous SMB Connection'],
    topFeatures: ['auth_failures:high', 'subsequent_auth_success:true', 'protocol:smb'],
  },
  {
    id: 'alert-4',
    time: createDeterministicTimestamp(today, 3),
    host: 'DEV-STATION-11',
    alertType: 'Beaconing',
    score: 0.64,
    mitreTactic: 'TA0011',
    srcIp: '10.0.0.14',
    dstIp: '198.51.100.10',
    evidence: 'Periodic connection every 60s to known C2 IP over port 8443',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.6,
    supervisedClassifierScore: 0.5,
    topRuleHits: ['Periodic Network Beaconing', 'Connection to Known C2'],
    topFeatures: ['interval_std_dev:0.1s', 'dst_port:8443', 'dst_ip:198.51.100.10'],
  },
  {
    id: 'alert-5',
    time: createDeterministicTimestamp(today, 4),
    host: 'Mano-Linux-Debian',
    alertType: 'FileAccess',
    score: 0.55,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'High volume of read operations on directory /etc/shadow',
    status: 'Resolved',
    ruleBasedScore: 0.4,
    anomalyDetectionScore: 0.5,
    supervisedClassifierScore: 0.6,
    topRuleHits: ['High-frequency file access'],
    topFeatures: ['file_path:/etc/shadow', 'operation_count_read:high', 'process:cat'],
  },
  {
    id: 'alert-6',
    time: createDeterministicTimestamp(today, 5),
    host: 'Mano-Linux-Debian',
    alertType: 'DNSExfiltration',
    score: 0.91,
    mitreTactic: 'TA0010',
    srcIp: '10.214.252.85',
    dstIp: '8.8.8.8',
    evidence: 'Unusually long DNS query with high entropy to subdomain of acme-data.xyz',
    status: 'New',
    ruleBasedScore: 0.95,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.92,
    topRuleHits: ['DNS Tunneling Heuristic', 'High-entropy Subdomain'],
    topFeatures: ['domain:acme-data.xyz', 'query_length>100', 'entropy:high'],
  },
  {
    id: 'alert-7',
    time: createDeterministicTimestamp(today, 6),
    host: 'Strive-Linux',
    alertType: 'FileStaging',
    score: 0.82,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'Large archive created: /tmp/backup.zip (Size: 250MB)',
    status: 'Investigating',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['Large Archive Creation', 'Staging in Non-standard Directory'],
    topFeatures: ['file_path:/tmp', 'file_ext:.zip', 'size_mb>200'],
  },
  {
    id: 'alert-8',
    time: createDeterministicTimestamp(today, 7),
    host: 'DB-SERVER-01',
    alertType: 'NetworkAnomaly',
    score: 0.71,
    mitreTactic: 'TA0008',
    srcIp: '10.0.0.8',
    dstIp: '10.0.2.25',
    evidence: 'Successful RDP connection from a host in the developer subnet',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.75,
    supervisedClassifierScore: 0.68,
    topRuleHits: ['Anomalous RDP Connection', 'Cross-subnet Logon'],
    topFeatures: ['protocol:RDP', 'src_subnet:dev', 'dst_asset_type:database'],
  },
  {
    id: 'alert-9',
    time: createDeterministicTimestamp(yesterday, 0),
    host: 'DEV-STATION-11',
    alertType: 'ProcessAnomaly',
    score: 0.88,
    mitreTactic: 'TA0002',
    srcIp: '10.0.0.14',
    dstIp: '-',
    evidence: 'Scheduled task executed encoded PowerShell command',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.85,
    supervisedClassifierScore: 0.89,
    topRuleHits: ['Encoded PowerShell Command', 'Execution via Scheduled Task'],
    topFeatures: ['process:powershell.exe', 'cmdline_contains:-enc', 'parent:taskhostw.exe'],
  },
  {
    id: 'alert-10',
    time: createDeterministicTimestamp(yesterday, 1),
    host: 'WEB-SERVER-03',
    alertType: 'NetworkAnomaly',
    score: 0.62,
    mitreTactic: 'TA0011',
    srcIp: '10.10.1.5',
    dstIp: '203.0.113.88',
    evidence: 'Connection to a non-standard port (31337) on an unknown external IP',
    status: 'New',
    ruleBasedScore: 0.6,
    anomalyDetectionScore: 0.65,
    supervisedClassifierScore: 0.61,
    topRuleHits: ['Connection to Uncommon Port'],
    topFeatures: ['dst_port:31337', 'dst_ip_reputation:unknown'],
  },
  {
    id: 'alert-11',
    time: createDeterministicTimestamp(yesterday, 2),
    host: 'Mano-Linux-Debian',
    alertType: 'ProcessAnomaly',
    score: 0.79,
    mitreTactic: 'TA0003',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'New cron job created for user www-data executing /tmp/update.sh',
    status: 'Investigating',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.82,
    topRuleHits: ['Suspicious Cron Job Creation', 'Execution from /tmp'],
    topFeatures: ['user:www-data', 'cron_path:/tmp/update.sh', 'event:cron_create'],
  },
  {
    id: 'alert-12',
    time: createDeterministicTimestamp(yesterday, 3),
    host: 'Strive-Linux',
    alertType: 'Beaconing',
    score: 0.85,
    mitreTactic: 'TA0011',
    srcIp: '10.214.252.84',
    dstIp: 'pastebin.com',
    evidence: 'HTTP POST requests to pastebin.com every 5 minutes with small payloads',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.86,
    topRuleHits: ['Beaconing to Paste Site'],
    topFeatures: ['domain:pastebin.com', 'http_method:POST', 'interval:5m'],
  },
  {
    id: 'alert-13',
    time: createDeterministicTimestamp(yesterday, 4),
    host: 'Strive-Linux',
    alertType: 'LateralMovement',
    score: 0.93,
    mitreTactic: 'TA0008',
    srcIp: '10.214.252.84',
    dstIp: '10.0.0.8',
    evidence: 'PsExec executed targeting DB-SERVER-01 from a client machine',
    status: 'New',
    ruleBasedScore: 0.95,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.92,
    topRuleHits: ['PsExec Execution Detected'],
    topFeatures: ['tool:psexec.exe', 'src_host:Strive-Linux', 'dst_host:DB-SERVER-01'],
  },
  {
    id: 'alert-14',
    time: createDeterministicTimestamp(yesterday, 5),
    host: 'DB-SERVER-01',
    alertType: 'DataExfiltration',
    score: 0.99,
    mitreTactic: 'TA0010',
    srcIp: '10.0.0.8',
    dstIp: '1.1.1.1',
    evidence: 'Large ICMP packets detected, indicating potential ICMP tunneling',
    status: 'New',
    ruleBasedScore: 0.98,
    anomalyDetectionScore: 0.99,
    supervisedClassifierScore: 0.99,
    topRuleHits: ['ICMP Tunneling Detected'],
    topFeatures: ['protocol:ICMP', 'packet_size:large', 'dst_ip_reputation:suspicious'],
  },
  {
    id: 'alert-15',
    time: createDeterministicTimestamp(yesterday, 6),
    host: 'DEV-STATION-11',
    alertType: 'FileAccess',
    score: 0.68,
    mitreTactic: 'TA0007',
    srcIp: '10.0.0.14',
    dstIp: '-',
    evidence: 'Process lsass.exe memory was dumped by non-system process',
    status: 'Investigating',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.6,
    supervisedClassifierScore: 0.7,
    topRuleHits: ['LSASS Memory Dump'],
    topFeatures: ['target_process:lsass.exe', 'source_process:procdump.exe'],
  },
  {
    id: 'alert-16',
    time: createDeterministicTimestamp(today, 8),
    host: 'WEB-SERVER-03',
    alertType: 'ProcessAnomaly',
    score: 0.84,
    mitreTactic: 'TA0003',
    srcIp: '10.10.1.5',
    dstIp: '-',
    evidence: 'Web server process (nginx) spawned a shell (/bin/sh)',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['Web Server Spawning Shell'],
    topFeatures: ['parent:nginx', 'child:/bin/sh'],
  },
  {
    id: 'alert-17',
    time: createDeterministicTimestamp(today, 9),
    host: 'Mano-Linux-Debian',
    alertType: 'LateralMovement',
    score: 0.77,
    mitreTactic: 'TA0008',
    srcIp: '10.214.252.85',
    dstIp: '10.214.252.84',
    evidence: 'SSH connection with key-based auth from unusual source',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.75,
    topRuleHits: ['Anomalous Internal SSH'],
    topFeatures: ['protocol:ssh', 'auth_type:pubkey', 'uncommon_src_dst_pair:true'],
  },
  {
    id: 'alert-18',
    time: createDeterministicTimestamp(today, 10),
    host: 'Strive-Linux',
    alertType: 'FileStaging',
    score: 0.75,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'Copied files from network share to local temp directory',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.8,
    topRuleHits: ['Copy from Network Share to Temp'],
    topFeatures: ['src_path:\\\\filesrv\\shares', 'dst_path:/tmp'],
  },
  {
    id: 'alert-19',
    time: createDeterministicTimestamp(yesterday, 7),
    host: 'DB-SERVER-01',
    alertType: 'NetworkAnomaly',
    score: 0.94,
    mitreTactic: 'TA0010',
    srcIp: '10.0.0.8',
    dstIp: '8.8.4.4',
    evidence: 'SQL database process initiated outbound connection to public DNS server',
    status: 'Investigating',
    ruleBasedScore: 0.95,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.93,
    topRuleHits: ['Database Making External Connection'],
    topFeatures: ['process:sqlserver.exe', 'dst_ip:8.8.4.4', 'dst_port:53'],
  },
  {
    id: 'alert-20',
    time: createDeterministicTimestamp(yesterday, 8),
    host: 'DEV-STATION-11',
    alertType: 'ProcessAnomaly',
    score: 0.81,
    mitreTactic: 'TA0005',
    srcIp: '10.0.0.14',
    dstIp: '-',
    evidence: 'The `wmic` utility was used to query for antivirus product information',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.75,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['WMIC Used for AV Discovery'],
    topFeatures: ['process:wmic.exe', 'cmdline_contains:antivirusproduct'],
  },
  {
    id: 'alert-21',
    time: createDeterministicTimestamp(yesterday, 9),
    host: 'Mano-Linux-Debian',
    alertType: 'NetworkAnomaly',
    score: 0.69,
    mitreTactic: 'TA0011',
    srcIp: '10.214.252.85',
    dstIp: 'github.com',
    evidence: 'Connection to GitHub over non-standard port 1337',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.65,
    supervisedClassifierScore: 0.7,
    topRuleHits: ['Non-Standard Port to Known Service'],
    topFeatures: ['domain:github.com', 'dst_port:1337'],
  },
  {
    id: 'alert-22',
    time: createDeterministicTimestamp(yesterday, 10),
    host: 'Strive-Linux',
    alertType: 'DataExfiltration',
    score: 0.88,
    mitreTactic: 'TA0010',
    srcIp: '10.214.252.84',
    dstIp: '45.77.65.123',
    evidence: 'Outbound SCP transfer of 50MB to an untrusted IP address',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.85,
    supervisedClassifierScore: 0.88,
    topRuleHits: ['Large SCP Outbound Transfer'],
    topFeatures: ['protocol:scp', 'bytes_sent>40MB', 'dst_ip_reputation:unknown'],
  },
  {
    id: 'alert-23',
    time: createDeterministicTimestamp(yesterday, 11),
    host: 'Strive-Linux',
    alertType: 'FileAccess',
    score: 0.72,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'VSSAdmin was used to create a shadow copy of the C: drive',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.6,
    supervisedClassifierScore: 0.75,
    topRuleHits: ['Volume Shadow Copy Creation'],
    topFeatures: ['process:vssadmin.exe', 'cmdline_contains:create shadow'],
  },
  {
    id: 'alert-24',
    time: createDeterministicTimestamp(yesterday, 12),
    host: 'DB-SERVER-01',
    alertType: 'ProcessAnomaly',
    score: 0.90,
    mitreTactic: 'TA0002',
    srcIp: '10.0.0.8',
    dstIp: '-',
    evidence: 'xp_cmdshell was enabled and used to execute a whoami command',
    status: 'Investigating',
    ruleBasedScore: 0.95,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.9,
    topRuleHits: ['xp_cmdshell execution'],
    topFeatures: ['db_function:xp_cmdshell', 'command:whoami'],
  },
  {
    id: 'alert-25',
    time: createDeterministicTimestamp(yesterday, 13),
    host: 'WEB-SERVER-03',
    alertType: 'DNSExfiltration',
    score: 0.86,
    mitreTactic: 'TA0010',
    srcIp: '10.10.1.5',
    dstIp: '8.8.8.8',
    evidence: 'High frequency of DNS TXT queries for different subdomains of evil-corp.net',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['High-Frequency DNS Tunneling'],
    topFeatures: ['dns_query_type:TXT', 'rate_per_min>100', 'domain:evil-corp.net'],
  },
  {
    id: 'alert-26',
    time: createDeterministicTimestamp(today, 11),
    host: 'Strive-Linux',
    alertType: 'LateralMovement',
    score: 0.82,
    mitreTactic: 'TA0008',
    srcIp: '10.214.252.84',
    dstIp: '10.214.252.85',
    evidence: 'WinRM connection established from client to another client',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['Anomalous WinRM Usage'],
    topFeatures: ['protocol:WinRM', 'src_role:workstation', 'dst_role:workstation'],
  },
  {
    id: 'alert-27',
    time: createDeterministicTimestamp(today, 12),
    host: 'DEV-STATION-11',
    alertType: 'Beaconing',
    score: 0.74,
    mitreTactic: 'TA0011',
    srcIp: '10.0.0.14',
    dstIp: '104.21.23.111',
    evidence: 'HTTPS connection to Cloudflare IP with JA3 hash associated with Cobalt Strike',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.6,
    supervisedClassifierScore: 0.7,
    topRuleHits: ['Cobalt Strike JA3 Hash Match'],
    topFeatures: ['ja3_hash:e7d4b4c5...', 'dst_ip_is_cdn:true'],
  },
  {
    id: 'alert-28',
    time: createDeterministicTimestamp(today, 13),
    host: 'Mano-Linux-Debian',
    alertType: 'FileStaging',
    score: 0.70,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'tar command used to archive /etc/ directory',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.65,
    supervisedClassifierScore: 0.75,
    topRuleHits: ['Archiving of Sensitive Directory'],
    topFeatures: ['process:tar', 'path:/etc/'],
  },
  {
    id: 'alert-29',
    time: createDeterministicTimestamp(today, 14),
    host: 'WEB-SERVER-03',
    alertType: 'DataExfiltration',
    score: 0.96,
    mitreTactic: 'TA0010',
    srcIp: '10.10.1.5',
    dstIp: 'ir-control.online',
    evidence: 'Outbound connection from web server to known C2 domain',
    status: 'Investigating',
    ruleBasedScore: 1.0,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.95,
    topRuleHits: ['Connection to Known C2 Domain'],
    topFeatures: ['domain:ir-control.online', 'dst_ip_reputation:malicious'],
  },
  {
    id: 'alert-30',
    time: createDeterministicTimestamp(today, 15),
    host: 'Mano-Linux-Debian',
    alertType: 'ProcessAnomaly',
    score: 0.89,
    mitreTactic: 'TA0005',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'bitsadmin.exe used to download file from untrusted source',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.9,
    topRuleHits: ['BITSAdmin for Download'],
    topFeatures: ['process:bitsadmin.exe', 'cmdline_contains:/transfer'],
  },
  {
    id: 'alert-31',
    time: createDeterministicTimestamp(yesterday, 14),
    host: 'DB-SERVER-01',
    alertType: 'FileAccess',
    score: 0.92,
    mitreTactic: 'TA0009',
    srcIp: '10.0.0.8',
    dstIp: '-',
    evidence: 'Database backup created in a web-accessible directory /var/www/html/backups',
    status: 'New',
    ruleBasedScore: 0.95,
    anomalyDetectionScore: 0.85,
    supervisedClassifierScore: 0.9,
    topRuleHits: ['DB Backup in Web Root'],
    topFeatures: ['file_path:/var/www/html', 'file_ext:.bak', 'process:sqlcmd'],
  },
  {
    id: 'alert-32',
    time: createDeterministicTimestamp(yesterday, 15),
    host: 'Strive-Linux',
    alertType: 'NetworkAnomaly',
    score: 0.73,
    mitreTactic: 'TA0001',
    srcIp: '192.168.1.101',
    dstIp: '10.214.252.84',
    evidence: 'Inbound connection from guest network to internal client machine',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.75,
    topRuleHits: ['Anomalous Network Zone Traversal'],
    topFeatures: ['src_zone:guest', 'dst_zone:internal', 'dst_port:445'],
  },
  {
    id: 'alert-33',
    time: createDeterministicTimestamp(yesterday, 16),
    host: 'DEV-STATION-11',
    alertType: 'Beaconing',
    score: 0.78,
    mitreTactic: 'TA0011',
    srcIp: '10.0.0.14',
    dstIp: 'api.telegram.org',
    evidence: 'Periodic HTTPS POSTs to Telegram API, potential C2 channel',
    status: 'Resolved',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.8,
    topRuleHits: ['C2 over Telegram API'],
    topFeatures: ['domain:api.telegram.org', 'interval:10m'],
  },
  {
    id: 'alert-34',
    time: createDeterministicTimestamp(yesterday, 17),
    host: 'Mano-Linux-Debian',
    alertType: 'ProcessAnomaly',
    score: 0.83,
    mitreTactic: 'TA0002',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'Hidden file execution from /var/tmp/.x11-unix',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['Execution of Hidden File'],
    topFeatures: ['file_path:/var/tmp', 'filename_startsWith:.'],
  },
  {
    id: 'alert-35',
    time: createDeterministicTimestamp(yesterday, 18),
    host: 'WEB-SERVER-03',
    alertType: 'LateralMovement',
    score: 0.90,
    mitreTactic: 'TA0008',
    srcIp: '10.10.1.5',
    dstIp: '10.0.0.8',
    evidence: 'Web server initiated SSH connection to internal database server',
    status: 'Investigating',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.9,
    topRuleHits: ['Anomalous Server-to-Server SSH'],
    topFeatures: ['src_role:web-server', 'dst_role:db-server', 'protocol:ssh'],
  },
  {
    id: 'alert-36',
    time: createDeterministicTimestamp(today, 16),
    host: 'Strive-Linux',
    alertType: 'DNSExfiltration',
    score: 0.89,
    mitreTactic: 'TA0010',
    srcIp: '10.214.252.84',
    dstIp: '8.8.8.8',
    evidence: 'Sequence of AAAA queries encoding data to a suspicious domain',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.85,
    supervisedClassifierScore: 0.9,
    topRuleHits: ['AAAA Record DNS Tunnel'],
    topFeatures: ['dns_query_type:AAAA', 'payload_encoding:hex'],
  },
  {
    id: 'alert-37',
    time: createDeterministicTimestamp(today, 17),
    host: 'DB-SERVER-01',
    alertType: 'FileStaging',
    score: 0.78,
    mitreTactic: 'TA0009',
    srcIp: '10.0.0.8',
    dstIp: '-',
    evidence: 'SQL Server process wrote an executable file to C:\\Windows\\Temp',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.8,
    topRuleHits: ['Database Process Writing Executable'],
    topFeatures: ['process:sqlserver.exe', 'file_path:C:\\Windows\\Temp', 'file_ext:.exe'],
  },
  {
    id: 'alert-38',
    time: createDeterministicTimestamp(today, 18),
    host: 'DEV-STATION-11',
    alertType: 'NetworkAnomaly',
    score: 0.67,
    mitreTactic: 'TA0011',
    srcIp: '10.0.0.14',
    dstIp: '40.117.132.146',
    evidence: 'Connection to Microsoft IP with self-signed certificate (potential C2)',
    status: 'New',
    ruleBasedScore: 0.6,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.65,
    topRuleHits: ['Suspicious SSL Certificate'],
    topFeatures: ['tls_cert_issuer:self-signed', 'dst_ip_owner:microsoft'],
  },
  {
    id: 'alert-39',
    time: createDeterministicTimestamp(today, 19),
    host: 'Mano-Linux-Debian',
    alertType: 'DataExfiltration',
    score: 0.95,
    mitreTactic: 'TA0010',
    srcIp: '10.214.252.85',
    dstIp: 'dropbox.com',
    evidence: 'Large upload to Dropbox by a server process',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.95,
    supervisedClassifierScore: 0.92,
    topRuleHits: ['Server Exfiltration to Cloud Storage'],
    topFeatures: ['domain:dropbox.com', 'process:apache2', 'bytes_sent>100MB'],
  },
  {
    id: 'alert-40',
    time: createDeterministicTimestamp(today, 20),
    host: 'Strive-Linux',
    alertType: 'ProcessAnomaly',
    score: 0.91,
    mitreTactic: 'TA0002',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'regsvr32.exe executed a remote script from a scrobj.dll file',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.92,
    topRuleHits: ['Regsvr32 Script Execution (Squiblydoo)'],
    topFeatures: ['process:regsvr32.exe', 'cmdline_contains:scrobj.dll'],
  },
  {
    id: 'alert-41',
    time: createDeterministicTimestamp(yesterday, 19),
    host: 'WEB-SERVER-03',
    alertType: 'FileAccess',
    score: 0.76,
    mitreTactic: 'TA0003',
    srcIp: '10.10.1.5',
    dstIp: '-',
    evidence: 'A web shell (cmd.aspx) was dropped in the web root directory',
    status: 'Investigating',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.8,
    topRuleHits: ['Web Shell Detected'],
    topFeatures: ['filename:cmd.aspx', 'file_path:/var/www/html'],
  },
  {
    id: 'alert-42',
    time: createDeterministicTimestamp(yesterday, 20),
    host: 'DB-SERVER-01',
    alertType: 'LateralMovement',
    score: 0.84,
    mitreTactic: 'TA0008',
    srcIp: '10.0.0.8',
    dstIp: '10.0.0.1',
    evidence: 'Database server made an outbound connection to the domain controller',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.88,
    topRuleHits: ['Anomalous DB to DC Connection'],
    topFeatures: ['src_role:db-server', 'dst_role:domain-controller'],
  },
  {
    id: 'alert-43',
    time: createDeterministicTimestamp(yesterday, 21),
    host: 'Mano-Linux-Debian',
    alertType: 'Beaconing',
    score: 0.71,
    mitreTactic: 'TA0011',
    srcIp: '10.214.252.85',
    dstIp: '194.58.104.182',
    evidence: 'DNS queries for a DGA (Domain Generation Algorithm) domain',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.75,
    topRuleHits: ['DGA Domain Detected'],
    topFeatures: ['dga_confidence:high', 'dns_query_pattern:randomized'],
  },
  {
    id: 'alert-44',
    time: createDeterministicTimestamp(yesterday, 22),
    host: 'DEV-STATION-11',
    alertType: 'DataExfiltration',
    score: 0.88,
    mitreTactic: 'TA0010',
    srcIp: '10.0.0.14',
    dstIp: 'gist.github.com',
    evidence: 'Large amount of text pasted to a private Gist on GitHub',
    status: 'Resolved',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.89,
    topRuleHits: ['Data Exfiltration via Gist'],
    topFeatures: ['domain:gist.github.com', 'http_method:POST', 'data_size:large'],
  },
  {
    id: 'alert-45',
    time: createDeterministicTimestamp(yesterday, 23),
    host: 'Strive-Linux',
    alertType: 'FileStaging',
    score: 0.79,
    mitreTactic: 'TA0009',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'User home directory was archived using zip with password protection',
    status: 'New',
    ruleBasedScore: 0.8,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.8,
    topRuleHits: ['Password-Protected Archive Creation'],
    topFeatures: ['process:zip', 'cmdline_contains:--password', 'path:/home/'],
  },
  {
    id: 'alert-46',
    time: createDeterministicTimestamp(today, 21),
    host: 'WEB-SERVER-03',
    alertType: 'NetworkAnomaly',
    score: 0.92,
    mitreTactic: 'TA0011',
    srcIp: '10.10.1.5',
    dstIp: '169.254.169.254',
    evidence: 'Server process attempted to access the cloud metadata service',
    status: 'Investigating',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.95,
    topRuleHits: ['Cloud Metadata Service Access'],
    topFeatures: ['dst_ip:169.254.169.254', 'process:node'],
  },
  {
    id: 'alert-47',
    time: createDeterministicTimestamp(today, 22),
    host: 'Strive-Linux',
    alertType: 'FileAccess',
    score: 0.85,
    mitreTactic: 'TA0003',
    srcIp: '10.214.252.84',
    dstIp: '-',
    evidence: 'A new startup script was added to the user\'s Startup folder',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.85,
    topRuleHits: ['Persistence via Startup Folder'],
    topFeatures: ['file_path:%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup'],
  },
  {
    id: 'alert-48',
    time: createDeterministicTimestamp(today, 23),
    host: 'DB-SERVER-01',
    alertType: 'LateralMovement',
    score: 0.87,
    mitreTactic: 'TA0008',
    srcIp: '10.0.0.8',
    dstIp: '10.214.252.85',
    evidence: 'Impacket script (wmiexec.py) used to connect from DB server to client',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.88,
    topRuleHits: ['Impacket Usage Detected'],
    topFeatures: ['user_agent:impacket', 'protocol:dcom'],
  },
  {
    id: 'alert-49',
    time: createDeterministicTimestamp(today, 24),
    host: 'DEV-STATION-11',
    alertType: 'DNSExfiltration',
    score: 0.93,
    mitreTactic: 'TA0010',
    srcIp: '10.0.0.14',
    dstIp: '8.8.8.8',
    evidence: 'DNS over HTTPS (DoH) used to a non-standard resolver',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.95,
    topRuleHits: ['Anomalous DoH Traffic'],
    topFeatures: ['protocol:DoH', 'resolver_ip:untrusted'],
  },
  {
    id: 'alert-50',
    time: createDeterministicTimestamp(today, 25),
    host: 'Mano-Linux-Debian',
    alertType: 'ProcessAnomaly',
    score: 0.97,
    mitreTactic: 'TA0004',
    srcIp: '10.214.252.85',
    dstIp: '-',
    evidence: 'Kernel module loaded from /tmp directory (potential rootkit)',
    status: 'New',
    ruleBasedScore: 1.0,
    anomalyDetectionScore: 0.9,
    supervisedClassifierScore: 0.98,
    topRuleHits: ['Kernel Module Load from /tmp'],
    topFeatures: ['process:insmod', 'module_path:/tmp/rootkit.ko'],
  },
];
